CREATE TABLE [dbo].[User]
(
	[UID] INT NOT NULL PRIMARY KEY, 
    [Fname] NVARCHAR(15) NOT NULL, 
    [MINIT] CHAR NULL, 
    [Lname] NVARCHAR(15) NOT NULL, 
    [DOB] DATETIME NOT NULL, 
    [SEX] CHAR NULL DEFAULT 'M', 
    [Email] NVARCHAR(50) NOT NULL, 
    [Phone] INT NULL,
	CONSTRAINT chk_user_sex CHECK( SEX IN('M', 'F')),
	CONSTRAINT chk_user_phone CHECK (Phone BETWEEN 11111111111 AND 99999999999)
)
